import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:quantocube/page/Homeowner/listing/contractor_profile.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/services.dart';
import 'package:quantocube/page/onboarding/splash_screen.dart';
import 'package:quantocube/tests/sample_classes.dart';
import 'firebase_options.dart'; // Ensure this file exists (Generated by `flutterfire configure`)
import 'package:quantocube/route/route_generator.dart';
import 'package:quantocube/theme.dart';

void main() async {
  await dotenv.load();
  WidgetsFlutterBinding.ensureInitialized();
  // Prevent the app from rotating to landscape mode
  SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: projectTheme,
      home: const SplashScreen(),
      navigatorObservers: [
        KeyboardDismissNavigatorObserver(),
      ],
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}

// Collapse the keyboard whenever a new page is opened
class KeyboardDismissNavigatorObserver extends NavigatorObserver {
  @override
  void didPop(Route route, Route? previousRoute) {
    FocusManager.instance.primaryFocus?.unfocus();
    super.didPop(route, previousRoute);
  }
}
