import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:quantocube/page/Homeowner/homeowner_homepage.dart';
import 'firebase_options.dart'; // Ensure this file exists (Generated by `flutterfire configure`)
import 'package:quantocube/page/onboarding/introduction_page.dart';
import 'package:quantocube/route/route_generator.dart';
import 'package:quantocube/theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
 
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: projectTheme,
      home: HomeownerHomePage(),
      navigatorObservers: [
        KeyboardDismissNavigatorObserver(),
      ],
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}

// Collapse the keyboard whenever a new page is opened
class KeyboardDismissNavigatorObserver extends NavigatorObserver {
  @override
  void didPop(Route route, Route? previousRoute) {
    FocusManager.instance.primaryFocus?.unfocus();
    super.didPop(route, previousRoute);
  }
}
